import { Transaction } from "@/types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  // January
  { id: "t1", date: "2024-01-02", amount: 85000, category: "Salary", type: "income", description: "Monthly salary", merchant: "Acme Corp" },
  { id: "t2", date: "2024-01-05", amount: 2400, category: "Food & Dining", type: "expense", description: "Grocery run", merchant: "BigBasket" },
  { id: "t3", date: "2024-01-07", amount: 800, category: "Transport", type: "expense", description: "Monthly metro pass", merchant: "DMRC" },
  { id: "t4", date: "2024-01-10", amount: 3200, category: "Shopping", type: "expense", description: "Winter clothing", merchant: "Myntra" },
  { id: "t5", date: "2024-01-12", amount: 15000, category: "Freelance", type: "income", description: "UI design project", merchant: "Client A" },
  { id: "t6", date: "2024-01-14", amount: 1200, category: "Entertainment", type: "expense", description: "OTT subscriptions", merchant: "Netflix/Prime" },
  { id: "t7", date: "2024-01-18", amount: 18000, category: "Housing", type: "expense", description: "Monthly rent", merchant: "Landlord" },
  { id: "t8", date: "2024-01-20", amount: 4500, category: "Utilities", type: "expense", description: "Electricity & internet", merchant: "BSES/Airtel" },
  { id: "t9", date: "2024-01-22", amount: 2800, category: "Food & Dining", type: "expense", description: "Restaurants & Zomato", merchant: "Zomato" },
  { id: "t10", date: "2024-01-25", amount: 8000, category: "Investment", type: "income", description: "Mutual fund returns", merchant: "Zerodha" },
  { id: "t11", date: "2024-01-28", amount: 1500, category: "Healthcare", type: "expense", description: "Doctor visit & meds", merchant: "Apollo Clinic" },
  // February
  { id: "t12", date: "2024-02-01", amount: 85000, category: "Salary", type: "income", description: "Monthly salary", merchant: "Acme Corp" },
  { id: "t13", date: "2024-02-03", amount: 2100, category: "Food & Dining", type: "expense", description: "Grocery run", merchant: "Zepto" },
  { id: "t14", date: "2024-02-06", amount: 800, category: "Transport", type: "expense", description: "Monthly metro pass", merchant: "DMRC" },
  { id: "t15", date: "2024-02-10", amount: 5500, category: "Shopping", type: "expense", description: "Electronics", merchant: "Croma" },
  { id: "t16", date: "2024-02-12", amount: 12000, category: "Freelance", type: "income", description: "Logo branding project", merchant: "Client B" },
  { id: "t17", date: "2024-02-14", amount: 3600, category: "Entertainment", type: "expense", description: "Valentine's dinner + gifts", merchant: "Various" },
  { id: "t18", date: "2024-02-18", amount: 18000, category: "Housing", type: "expense", description: "Monthly rent", merchant: "Landlord" },
  { id: "t19", date: "2024-02-20", amount: 4200, category: "Utilities", type: "expense", description: "Electricity & internet", merchant: "BSES/Airtel" },
  { id: "t20", date: "2024-02-22", amount: 1800, category: "Food & Dining", type: "expense", description: "Restaurants", merchant: "Swiggy" },
  { id: "t21", date: "2024-02-26", amount: 6000, category: "Education", type: "expense", description: "Online courses", merchant: "Udemy" },
  // March
  { id: "t22", date: "2024-03-01", amount: 85000, category: "Salary", type: "income", description: "Monthly salary", merchant: "Acme Corp" },
  { id: "t23", date: "2024-03-04", amount: 2600, category: "Food & Dining", type: "expense", description: "Grocery run", merchant: "BigBasket" },
  { id: "t24", date: "2024-03-07", amount: 800, category: "Transport", type: "expense", description: "Monthly metro pass", merchant: "DMRC" },
  { id: "t25", date: "2024-03-09", amount: 20000, category: "Travel", type: "expense", description: "Goa trip", merchant: "MakeMyTrip" },
  { id: "t26", date: "2024-03-12", amount: 18000, category: "Freelance", type: "income", description: "App development", merchant: "Client C" },
  { id: "t27", date: "2024-03-15", amount: 1200, category: "Entertainment", type: "expense", description: "Concerts & events", merchant: "BookMyShow" },
  { id: "t28", date: "2024-03-18", amount: 18000, category: "Housing", type: "expense", description: "Monthly rent", merchant: "Landlord" },
  { id: "t29", date: "2024-03-21", amount: 4800, category: "Utilities", type: "expense", description: "Electricity & internet", merchant: "BSES/Airtel" },
  { id: "t30", date: "2024-03-24", amount: 9500, category: "Shopping", type: "expense", description: "Holi shopping", merchant: "Amazon" },
  { id: "t31", date: "2024-03-27", amount: 12000, category: "Investment", type: "income", description: "Stock dividends", merchant: "Zerodha" },
  { id: "t32", date: "2024-03-29", amount: 3200, category: "Food & Dining", type: "expense", description: "Holi celebrations", merchant: "Various" },
  // April
  { id: "t33", date: "2024-04-01", amount: 85000, category: "Salary", type: "income", description: "Monthly salary", merchant: "Acme Corp" },
  { id: "t34", date: "2024-04-05", amount: 2300, category: "Food & Dining", type: "expense", description: "Grocery run", merchant: "BigBasket" },
  { id: "t35", date: "2024-04-08", amount: 800, category: "Transport", type: "expense", description: "Monthly metro pass", merchant: "DMRC" },
  { id: "t36", date: "2024-04-10", amount: 4200, category: "Healthcare", type: "expense", description: "Annual health checkup", merchant: "Fortis" },
  { id: "t37", date: "2024-04-15", amount: 10000, category: "Freelance", type: "income", description: "Content strategy", merchant: "Client D" },
  { id: "t38", date: "2024-04-18", amount: 18000, category: "Housing", type: "expense", description: "Monthly rent", merchant: "Landlord" },
  { id: "t39", date: "2024-04-20", amount: 4500, category: "Utilities", type: "expense", description: "Electricity & internet", merchant: "BSES/Airtel" },
  { id: "t40", date: "2024-04-22", amount: 7800, category: "Shopping", type: "expense", description: "Summer wardrobe", merchant: "H&M" },
  { id: "t41", date: "2024-04-25", amount: 1600, category: "Entertainment", type: "expense", description: "IPL match tickets", merchant: "BookMyShow" },
  // May
  { id: "t42", date: "2024-05-01", amount: 90000, category: "Salary", type: "income", description: "Monthly salary (appraisal)", merchant: "Acme Corp" },
  { id: "t43", date: "2024-05-04", amount: 2700, category: "Food & Dining", type: "expense", description: "Grocery run", merchant: "Zepto" },
  { id: "t44", date: "2024-05-07", amount: 800, category: "Transport", type: "expense", description: "Monthly metro pass", merchant: "DMRC" },
  { id: "t45", date: "2024-05-10", amount: 25000, category: "Travel", type: "expense", description: "Manali trip", merchant: "Cleartrip" },
  { id: "t46", date: "2024-05-14", amount: 20000, category: "Freelance", type: "income", description: "Dashboard project", merchant: "Client E" },
  { id: "t47", date: "2024-05-18", amount: 18000, category: "Housing", type: "expense", description: "Monthly rent", merchant: "Landlord" },
  { id: "t48", date: "2024-05-21", amount: 5200, category: "Utilities", type: "expense", description: "Electricity (summer) & internet", merchant: "BSES/Airtel" },
  { id: "t49", date: "2024-05-24", amount: 3400, category: "Food & Dining", type: "expense", description: "Restaurants", merchant: "Zomato" },
  { id: "t50", date: "2024-05-28", amount: 15000, category: "Investment", type: "income", description: "SIP returns", merchant: "Zerodha" },
  // June
  { id: "t51", date: "2024-06-01", amount: 90000, category: "Salary", type: "income", description: "Monthly salary", merchant: "Acme Corp" },
  { id: "t52", date: "2024-06-05", amount: 2500, category: "Food & Dining", type: "expense", description: "Grocery run", merchant: "BigBasket" },
  { id: "t53", date: "2024-06-07", amount: 800, category: "Transport", type: "expense", description: "Monthly metro pass", merchant: "DMRC" },
  { id: "t54", date: "2024-06-12", amount: 8000, category: "Shopping", type: "expense", description: "Monsoon essentials", merchant: "Amazon" },
  { id: "t55", date: "2024-06-15", amount: 22000, category: "Freelance", type: "income", description: "E-commerce redesign", merchant: "Client F" },
  { id: "t56", date: "2024-06-18", amount: 18000, category: "Housing", type: "expense", description: "Monthly rent", merchant: "Landlord" },
  { id: "t57", date: "2024-06-20", amount: 4000, category: "Utilities", type: "expense", description: "Electricity & internet", merchant: "BSES/Airtel" },
  { id: "t58", date: "2024-06-24", amount: 2200, category: "Entertainment", type: "expense", description: "OTTs & gaming", merchant: "Steam/Netflix" },
  { id: "t59", date: "2024-06-28", amount: 1800, category: "Food & Dining", type: "expense", description: "Restaurants", merchant: "Swiggy" },
];

export const CATEGORY_COLORS: Record<string, string> = {
  "Salary": "#10b981",
  "Freelance": "#34d399",
  "Investment": "#6ee7b7",
  "Food & Dining": "#f59e0b",
  "Transport": "#8b5cf6",
  "Shopping": "#ec4899",
  "Entertainment": "#06b6d4",
  "Healthcare": "#ef4444",
  "Housing": "#3b82f6",
  "Utilities": "#f97316",
  "Education": "#a855f7",
  "Travel": "#14b8a6",
  "Other": "#6b7280",
};
